"""Surface Python SDK — scan files for malware via the Surface API."""

from .client import AsyncSurfaceClient, SurfaceClient, verify_webhook_signature
from .decorator import MaliciousFileError, scan
from .middleware import ScanMiddleware, scan_request
from .errors import (
    AuthenticationError,
    NotFoundError,
    QuotaExceededError,
    RateLimitError,
    SurfaceError,
    ValidationError,
)
from .models import (
    APIKey,
    Account,
    AnalysisIndicator,
    ArchiveEntry,
    BoxJSFile,
    BoxJSResult,
    CapaATTACK,
    CapaCapability,
    CapaResult,
    CVEInfo,
    CreditTier,
    DailyVolume,
    DeferredScanResponse,
    DiEResult,
    FlossResult,
    IOC,
    MLClassifyResult,
    OletoolsResult,
    PDFAnalysisResult,
    PDFStreamInfo,
    Plan,
    SafetyScore,
    ScanHistoryEntry,
    ScanHistoryPage,
    ScanProfile,
    ScanResult,
    StaticAnalysisResult,
    TLSHResult,
    Usage,
    WebhookFile,
    WebhookPayload,
    YaraMatch,
    YaraScanResult,
    YaraStringMatch,
)

__all__ = [
    "AsyncSurfaceClient",
    "SurfaceClient",
    "scan",
    "MaliciousFileError",
    "verify_webhook_signature",
    # Errors
    "SurfaceError",
    "AuthenticationError",
    "NotFoundError",
    "QuotaExceededError",
    "RateLimitError",
    "ValidationError",
    # Middleware
    "ScanMiddleware",
    "scan_request",
    # Models
    "Account",
    "APIKey",
    "AnalysisIndicator",
    "ArchiveEntry",
    "BoxJSFile",
    "BoxJSResult",
    "CapaATTACK",
    "CapaCapability",
    "CapaResult",
    "CVEInfo",
    "CreditTier",
    "DailyVolume",
    "DeferredScanResponse",
    "DiEResult",
    "FlossResult",
    "IOC",
    "MLClassifyResult",
    "OletoolsResult",
    "PDFAnalysisResult",
    "PDFStreamInfo",
    "Plan",
    "SafetyScore",
    "ScanHistoryEntry",
    "ScanHistoryPage",
    "ScanProfile",
    "ScanResult",
    "StaticAnalysisResult",
    "TLSHResult",
    "Usage",
    "WebhookFile",
    "WebhookPayload",
    "YaraMatch",
    "YaraScanResult",
    "YaraStringMatch",
]
